# Generated by Django 5.1.1 on 2024-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
