# Generated by Django 5.1.1 on 2024-09-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
