# Generated by Django 5.1.1 on 2024-09-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_profile_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='info',
            new_name='user_info',
        ),
    ]
