# Generated by Django 5.1.1 on 2024-09-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_info_profile_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.postcategory'),
            preserve_default=False,
        ),
    ]
